### ISSUE TITLE
#import "AlipayModule.h" file not found

### ISSUE THREAD

**Issue by Micjoyce** [myoula/react-native-payment-alipay#8]
已经在header search 添加了

$(SRCROOT)/../node_modules/react-native-payment-alipay/ios

**Comment by tyw2015** [comment]
已解决，把路径改成$(SRCROOT)/../node_modules/react-native-payment-alipay/ios/AlipayModule

**Comment by zhenliliu** [comment]
$(SRCROOT)/../node_modules/react-native-payment-alipay/ios/AlipayModule
引入的时候还是提示找不到
